; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[common]
platform = espressif32
framework = arduino
monitor_speed = 115200
build_flags =
  -D CORE_DEBUG_LEVEL=0         # For debugging set to 3 and enable debug mode in the app
  -Ofast                        # maximum speed!
lib_deps =
  SPI
  bodmer/TFT_eSPI
  https://github.com/bitbank2/JPEGDEC
  z3t0/IRremote
  bblanchon/ArduinoJson
monitor_filters =
  esp32_exception_decoder        # decode exceptions

[esp32_common]
platform = ${common.platform}
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
build_flags = ${common.build_flags}
lib_deps = ${common.lib_deps}
monitor_filters = ${common.monitor_filters}

[cyd-common]
build_flags =
  ${common.build_flags}
  -DUSE_DMA
  ; TFT_eSPI setup
  -DUSER_SETUP_LOADED
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=320
  -DILI9341_2_DRIVER
  -DTFT_SCLK=GPIO_NUM_14
  -DTFT_MISO=GPIO_NUM_12
  -DTFT_MOSI=GPIO_NUM_13
  -DTFT_RST=GPIO_NUM_NC
  -DTFT_DC=GPIO_NUM_2
  -DTFT_CS=GPIO_NUM_15
  -DTFT_BL=GPIO_NUM_21
  -DTFT_BACKLIGHT_ON=HIGH
  -DLOAD_FONT2=1
  -DSPI_FREQUENCY=55000000
  -DSPI_READ_FREQUENCY=20000000
  -DSPI_TOUCH_FREQUENCY=2500000
  ; audio settings - cheap yellow display uses the DAC
  ; CYD has terrible audio - but actually is quite good if you use PWM
  ; -DUSE_DAC_AUDIO
  -DPWM_GPIO_NUM=GPIO_NUM_26

[cyd]
extends = esp32_common
board = esp-wrover-kit
platform_packages =
  toolchain-xtensa-esp32 @ platformio/toolchain-xtensa-esp-elf @ 15.2.0+20251204
  platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.17
build_flags =
  ${cyd-common.build_flags}

[env:cyd-sd-ir]
extends = cyd
build_flags =
  ${cyd-common.build_flags}
  ; SD card
  -DUSE_SDCARD
  -DSD_CARD_MISO=GPIO_NUM_19
  -DSD_CARD_MOSI=GPIO_NUM_23
  -DSD_CARD_CLK=GPIO_NUM_18
  -DSD_CARD_CS=GPIO_NUM_5
  ; IR remote
  -DHAS_IR_REMOTE
  -DIR_RECV_PIN=GPIO_NUM_27
  -DIR_RECV_PWR=GPIO_NUM_NC
  -DIR_RECV_GND=GPIO_NUM_NC
  -DIR_RECV_IND=GPIO_NUM_NC

[env:cyd-embed]
extends = cyd
board_build.partitions = huge_app.csv
build_flags =
  ${cyd-common.build_flags}
  ; embed video
  -DUSE_EMBED
  -DEMBEDDED_VIDEO=video.avi
  -std=gnu++2b
  -include time.h
  -D'_SECTION_ATTR_IMPL(SECTION, COUNTER)=__attribute__((section(SECTION)))'
  -Wno-attributes
